# Generated by Django 3.2.4 on 2021-06-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210620_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
