# Generated by Django 3.2.4 on 2021-07-18 17:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210620_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format=None, keep_meta=True, quality=100, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
