# Generated by Django 3.2.4 on 2021-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
