# Generated by Django 3.2.4 on 2021-06-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
